/*!
  \class FlexTextImporter
  \ingroup IO
  \ingroup TextImport
  \brief This reads external .flextext files, adding the text entries into the database. Instantiated in Project. (Files that were generated by Gloss are read by FlexTextReader.)
*/

#ifndef FLEXTEXTIMPORTER_H
#define FLEXTEXTIMPORTER_H

#include "flextextreader.h"

class WritingSystem;

class FlexTextImporter : public FlexTextReader
{
public:
    explicit FlexTextImporter(Text * text);

    FlexTextReader::Result readFile(const QString & filepath);
};

#endif // FLEXTEXTIMPORTER_H
